### PR TITLE
FISH-552 Release notes 5.22.0

### PR DESCRIPTION
**Pull request by rdebusscher**

### CODE REVIEW

**Review by AlanRoth — APPROVED** [review]

**Comment by OndroMih** [comment]
currentVersion in antora.yml should be updated to 5.22.

**Review by OndroMih — CHANGES_REQUESTED** [review]
currentVersion in antora.yml should be updated to 5.22.

**Comment by rdebusscher** [comment]
Updating antora.yml is part of the release of the documentation, not part of adding the release notes itself.

**Comment by OndroMih** [comment]
> Updating antora.yml is part of the release of the documentation, not part of adding the release notes itself.

OK, I agree. The release documentation said otherwise, I've fixed it now and moved the antora.yml to the release docs step.

**Review by OndroMih — APPROVED** [review]

**Pull request merged**
