### PR TITLE
FISH-385 Multitenant OpenID Connect

### PR DESCRIPTION
**Pull request by OndroMih**
Community PR: https://github.com/payara/Payara-Community-Documentation/pull/191

Also copied the section "Logout Functionality" from Community, which was missing in Enterprise (added to 5.22.0 with FISH-433)

### CODE REVIEW

**Comment by Pandrex247** [comment]
MP 4.0 and security connectors removed from 5.29 - presumably this shouldn't be merged?

**Comment by OndroMih** [comment]
Not going to the upcoming release.

**Comment by OndroMih** [comment]
Need to copy the changes requested on the community PR before merging.

**Comment by OndroMih** [comment]
Updated with comments on the community PR. Ready for review and merging.

**Pull request merged**
